//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistProClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersistProClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deftab709{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\froman\fprq2\fcharset0 Times New Roman;}{\f2\fswiss\fcharset0 Arial;}}
        ///{\colortbl ;\red0\green0\blue128;\red0\green0\blue0;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\lang1033\b\f0\fs24 Backup Explorer\par
        ///\b0\fs20\par
        ///Backup Explorer contains a hierarchical list of all of your backup folders and files. Backup Explorer displays the folders and files from your last backup in green. Folders and files t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BackupExplorerHelp {
            get {
                return ResourceManager.GetString("BackupExplorerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConceptLogo_NoBackGround_new {
            get {
                object obj = ResourceManager.GetObject("ConceptLogo_NoBackGround_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ConceptLogo_NoBackGround_Orange {
            get {
                object obj = ResourceManager.GetObject("ConceptLogo_NoBackGround_Orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fswiss\fcharset0 Arial;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 Thank you for choosing PersistPro!\b0\fs20\par
        ///\par
        ///Please enter a \cf1 Password\cf0 . This will be used to encrypt all of you data so you know it will be safe where ever you choose to store it.\par
        ///\par
        ///Select \cf1 Quick Setup Option \cf0 if you want a sample backup plan built.\par
        ///\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfigureHelp {
            get {
                return ResourceManager.GetString("ConfigureHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fswiss\fcharset0 Arial;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 External Drive\b0\fs20\par
        ///\par
        ///Enter a \cf1 Name\cf0  that will easily tell you what device is being used. Examples: &apos;My External HD&apos; or &apos;USB Stick&apos;.\par
        ///\par
        ///Select your drives \cf1 External Drive Label \cf0 from the drop down. If your drive is not present then please connect it to y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExternalDriveMountHelp {
            get {
                return ResourceManager.GetString("ExternalDriveMountHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fswiss\fcharset0 Arial;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 File Share\b0\fs20\par
        ///\par
        ///Enter a \cf1 Name\cf0  that will easily tell you where your backup is saved. Examples: &apos;My File Server&apos; or &apos;Local Hard Disk&apos;.\par
        ///\par
        ///Enter the \cf1 Path\cf0  where you want your data to be stored. Alternatively, select \cf1 Browse\cf0  to choose your \cf1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileMountHelp {
            get {
                return ResourceManager.GetString("FileMountHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fswiss\fcharset0 Arial;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 FTP\b0\fs20\par
        ///\par
        ///Enter a \cf1 Name\cf0  that will easily tell you what ftp site is being used. Examples: &apos;FTP mydata.com (Mike)&apos; or &apos;192.168.1.1&apos;.\par
        ///\par
        ///Enter the \cf1 Server\cf0  where your backup is saved. Examples: &apos;ftp.mydata.com&apos; or &apos;192.168.1.1&apos;.\par
        ///\par
        ///Enter the \cf1  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FtpMountHelp {
            get {
                return ResourceManager.GetString("FtpMountHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap install_banner {
            get {
                object obj = ResourceManager.GetObject("install_banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 Where to Backup your Data\b0\fs20\par
        ///\par
        ///Listed are all of the locations where your backups may be stored. \par
        ///\par
        ///Select \cf1 New\cf0  if you want to create a new location. Now \cf1 Select where you want your backup to go\cf0 . See below for an explaination of all the options. After selecting the type of loca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MountManagerHelp {
            get {
                return ResourceManager.GetString("MountManagerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NotifyIconError {
            get {
                object obj = ResourceManager.GetObject("NotifyIconError", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NotifyIconOK {
            get {
                object obj = ResourceManager.GetObject("NotifyIconOK", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon persistpro_icon_final {
            get {
                object obj = ResourceManager.GetObject("persistpro_icon_final", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap persistpro_logo_new48 {
            get {
                object obj = ResourceManager.GetObject("persistpro_logo_new48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PersistProBanner {
            get {
                object obj = ResourceManager.GetObject("PersistProBanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff1\adeflang1025
        ///{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}{\f1\froman\fprq2\fcharset0 Times New Roman;}{\f2\fswiss\fprq2\fcharset0 Arial;}{\f3\fswiss\fprq2\fcharset0 Arial;}{\f4\fswiss\fprq2\fcharset0 Futura Book;}{\f5\fnil\fprq0\fcharset0 Futura Bold;}{\f6\fswiss\fprq2\fcharset0 Tahoma;}{\f7\froman\fprq2\fcharset2 Symbol;}{\f8\fmodern\fprq1\fcharset0 Courier New;}{\f9\fnil\fprq2\fcharset2 Wingdings;}{\f10\froman\fprq2\fcharset0 Times New Roman;}{\f11\fnil\fprq2\fcharset0 MS Minc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PersistProEULA {
            get {
                return ResourceManager.GetString("PersistProEULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 Backup Tasks\b0\fs20\par
        ///\par
        ///Select \cf1 View Status / History \cf0 to see all upcoming scheduled backups and view a history of previous backups. You can also request that a backup occur now or abort an errored backup.\par
        ///\par
        ///Select \cf1 Restore Backup \cf0 to retrieve your files that have been saved.\par
        ///\par [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PersistProManagerHelp {
            get {
                return ResourceManager.GetString("PersistProManagerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 What, Where, When to Backup your Data\b0\fs20\par
        ///\par
        ///Select \cf1 What data do you want to backup\cf0  from the drop down. If the data is not present or you want to modify an existing source, select \cf1 Manage What\cf0 .\par
        ///\par
        ///Select \cf1 Where do you want to backup your data\cf0  from the drop down. If the l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlanHelp {
            get {
                return ResourceManager.GetString("PlanHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 Manage your Backup Plans\b0\fs20\par
        ///\par
        ///Listed are all of your backup plans answering What, Where, and When. \par
        ///\par
        ///Select \cf1 New\cf0  if you want to create a new backup plan.\par
        ///\par
        ///After selecting an existing backup plan, select \cf1 Edit\cf0  if you want to change the answers to What, Where, or When  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlanManagerHelp {
            get {
                return ResourceManager.GetString("PlanManagerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pp_conceptwithicon_new {
            get {
                object obj = ResourceManager.GetObject("pp_conceptwithicon_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pp_conceptwithicon_new2 {
            get {
                object obj = ResourceManager.GetObject("pp_conceptwithicon_new2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pp_logowithicon {
            get {
                object obj = ResourceManager.GetObject("pp_logowithicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff0\adeflang1025
        ///{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}{\f1\froman\fprq2\fcharset0 Times New Roman;}{\f2\fswiss\fprq2\fcharset0 Arial;}{\f3\fswiss\fprq2\fcharset0 Verdana;}{\f4\fnil\fprq2\fcharset0 Arial Unicode MS;}{\f5\fnil\fprq2\fcharset0 MS Mincho;}{\f6\fnil\fprq2\fcharset0 Tahoma;}{\f7\fnil\fprq0\fcharset0 Tahoma;}}
        ///{\colortbl;\red0\green0\blue0;\red0\green0\blue128;\red128\green128\blue128;}
        ///{\stylesheet{\s1\cf0{\*\hyphen2\hyphlead2\hyphtrail2\hyphmax0}\rtlch\af6\afs24 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuickRestoreHelp {
            get {
                return ResourceManager.GetString("QuickRestoreHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff0\adeflang1025
        ///{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}{\f1\froman\fprq2\fcharset0 Times New Roman;}{\f2\fswiss\fprq2\fcharset0 Arial;}{\f3\fswiss\fprq2\fcharset0 Verdana;}{\f4\fnil\fprq2\fcharset0 Arial Unicode MS;}{\f5\fnil\fprq2\fcharset0 MS Mincho;}{\f6\fnil\fprq2\fcharset0 Tahoma;}{\f7\fnil\fprq0\fcharset0 Tahoma;}}
        ///{\colortbl;\red0\green0\blue0;\red0\green0\blue128;\red128\green128\blue128;}
        ///{\stylesheet{\s1\cf0{\*\hyphen2\hyphlead2\hyphtrail2\hyphmax0}\rtlch\af6\afs24 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RestoreSelectorHelp {
            get {
                return ResourceManager.GetString("RestoreSelectorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fswiss\fcharset0 Arial;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 Setting File Attribute Filters\b0\fs20\par
        ///\par
        ///Listed are all of your file attribute filters. \par
        ///\par
        ///Select \cf1 Add\cf0  if you want to create a new file attribute filter.\par
        ///\par
        ///After selecting an existing file attribute filter, edit it by changing the \cf1 Filter Action\cf0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RootAttributeFilterHelp {
            get {
                return ResourceManager.GetString("RootAttributeFilterHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 What do you want to Backup\b0\fs20\par
        ///\par
        ///Enter a \cf1 Name\cf0  that will easily tell you what data is being saved. Examples: &apos;My Documents&apos; or &apos;Tax Returns&apos;.\par
        ///\par
        ///Enter the \cf1 Path\cf0  where you data is stored. Alternatively, select \cf1 Browse\cf0  to choose your \cf1 Path\cf0 .\par
        ///\par
        ///Select if yo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RootHelp {
            get {
                return ResourceManager.GetString("RootHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 What do you want to Backup\b0\fs20\par
        ///\par
        ///Listed are all of your locations that you want stored. \par
        ///\par
        ///Select \cf1 New\cf0  if you want to create a new backup location.\par
        ///\par
        ///After selecting an existing backup location, select \cf1 Edit\cf0  if you want to change the answers for this backup location or  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RootManagerHelp {
            get {
                return ResourceManager.GetString("RootManagerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fswiss\fcharset0 Arial;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 Setting File Name Filters\b0\fs20\par
        ///\par
        ///Listed are all of your file name filters. \par
        ///\par
        ///Select \cf1 Add\cf0  if you want to create a new file name filter.\par
        ///\par
        ///After selecting an existing file name filter, edit it by changing the \cf1 Filter Action\cf0  drop down and the \ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RootNameFilterHelp {
            get {
                return ResourceManager.GetString("RootNameFilterHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fswiss\fcharset0 Arial;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 When do you want to Backup your data\b0\fs20\par
        ///\par
        ///\cf1 This is the name of your schedule\cf0  will automatically be created for you.\par
        ///\par
        ///Select \cf1 How often do you want to backup \cf0 from the dropdown. You may choose Daily, Weekly, or Monthly.\par
        ///\par
        ///Answer \cf1 When do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScheduleHelp {
            get {
                return ResourceManager.GetString("ScheduleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fswiss\fcharset0 Arial;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 When do you want to Backup your data\par
        ///\b0\fs20\par
        ///Listed are all of your times that you want your backup to occur. \par
        ///\par
        ///Select \cf1 New\cf0  if you want to create a new time.\par
        ///\par
        ///After selecting an existing time, select \cf1 Edit\cf0  if you want to change this time or  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScheduleManagerHelp {
            get {
                return ResourceManager.GetString("ScheduleManagerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Verdana;}{\f1\fswiss\fcharset0 Arial;}}
        ///{\colortbl ;\red0\green0\blue128;}
        ///{\*\generator Msftedit 5.41.21.2508;}\viewkind4\uc1\pard\b\f0\fs24 Status\par
        ///\b0\fs20\par
        ///Listed are all of your backups that are currently scheduled. If you have check \cf1 View History \cf0 you will see your backup history as well.\par
        ///\par
        ///Select \cf1 Refresh \cf0 to update you backup list.\par
        ///\par
        ///After selecting a scheduled backup, select \cf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatusViewHelp {
            get {
                return ResourceManager.GetString("StatusViewHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WabiLogic_NoBackGround {
            get {
                object obj = ResourceManager.GetObject("WabiLogic_NoBackGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WabiLogo_no_background {
            get {
                object obj = ResourceManager.GetObject("WabiLogo_no_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
